[[create-panels]]
= Create panels

{kib} provides you with several visualization editors to create panels of your data. 
Each editor supports different features and {ref}/search-aggregations.html[{es} aggregations]. 

[float]
[[create-visualization-panels]]
== Create visualization panels

With the drag-and-drop visualization editor, you drag the data fields you want to visualize to the workspace, 
then visualization best practices are used to apply the fields and create a visualization that best displays your data. 

* Create area, line, and bar charts with layers to display multiple indices and chart types as the same time.
* Change the aggregation function to change the data in the visualization.
* Create custom tables and metrics.
* Perform math on aggregations using *Formula*.
* Use time shifts to compare the data in two time intervals, such as month over month.
* Add annotations and reference lines to important data.

--
include::lens.asciidoc[]

include::create-text-panels.asciidoc[]

include::create-image-panels.asciidoc[]